### ISSUE TITLE
Display-agnostic (OLED and LCD) builds

### ISSUE THREAD

**Issue by hattesen** [deividAlfa/stm32_soldering_iron_controller#27]
Given that the current builds already have surpassed 64k code requirements, it would seem relatively trivial to provide display-agnostic builds that include both OLED and LCD drivers, and detect which type of display is connected at startup?

This would reduce the number of builds and binary artifacts, thus simplifying the project structure without necessarily increasing the code complexity or impacting runtime performance.

I may be overlooking some obvious reasons why this may not be feasible, such as static RAM allocation requirements for the display libraries.

**Comment by deividAlfa** [comment]
Display controllers can't be read in SPI mode, so no way of detection, check the datasheets and you'll find out.
Reading works in I2C mode, but as the LCD works only with SPI, it's useless, also that's why KSGER v2 is OLED-only.
Supporting both wouldn't cause any major impact in the memory footprint, buffer is the same, only the commands change.
Closing for the said reasons. Feel free to reopen if you find something.
