### ISSUE TITLE
Data in flash and  versions of release for compatibilities

### ISSUE THREAD

**Issue by vlk3ru** [deividAlfa/stm32_soldering_iron_controller#70]
The data stored as separate block in flash incompatible from 1.10.6 to 1.10.8 versions ?

**Comment by deividAlfa** [comment]
Yes, existing data will be deleted.

**Comment by Doyle4** [comment]
I was on latest Firmware previous to 1.10.6 release then updated to 1.10.6, yet to update to 1.10.8.
When I flashed from previous firmware to 1.10.8 will I need to recalibrate my tip again or was that flash an upgrade? If needs calibrating again I'll update to latest then do it, so not doing it twice.
I noticed the boot screen changed when I did do the 1.10.6 update where as when I changed the boot screen and flashed same firmware all settings stayed the same.

Thanks :)

**Comment by deividAlfa** [comment]
Not sure, I have to check that.
System settings will be erased, but tips might survive.

**Comment by deividAlfa** [comment]
Update: Yes it will!
This was inherited from the older storage structure method.

Fixed in 65c6fa9d9522f6f69b851909a0c30dc049e472f5.

From now on, unless the profile structure changes (It didn't for a long time), profile data won't be wiped anymore.
Thus, when an older settings version is detected, it will only erase system settings, and the setup screen will be shown, but all the profiles will still be there.

New release : v1.11.0
https://github.com/deividAlfa/stm32_soldering_iron_controller/releases/tag/v.1.11.0

**Comment by deividAlfa** [comment]
Closing as solved.

**Comment by Doyle4** [comment]
Amazing, thank you.
